echo "We are trying this practical from linux EC2"
echo "I am from Young minds"
echo "We are from batch-27 and learning DevOps"
echo "Adding new Data"
echo "I am Using Github & Git"
echo "I am working in REQ01111"
echo "Adding new line"